### ISSUE TITLE
Update for kalliope v0.6

### ISSUE THREAD

**Issue by Sispheor** [kalliope-project/kalliope_neuron_answer_of_everything#7]
Need to check if this neuron is ok for python 3.
I think [encode ](https://github.com/kalliope-project/kalliope_neuron_answer_of_everything/blob/master/answer_of_everything.py#L137) method is not anymore present

**Comment by corus87** [comment]
Its working for python3, but I will change the code a bit when Kalliope 0.6 is released because Python 3 preserves the order of a dictionary so we don't need the priority parameter any more. 

For the encode method, according to the [python3 docs](https://docs.python.org/3/library/stdtypes.html#str.encode) it is still present?

**Comment by Sispheor** [comment]
Yes you are right. It's still there. 
It seems ok then. 
You will have to update the install like [this one to use pip3](https://github.com/kalliope-project/kalliope_signal_gpio_input/blob/master/install.yml)

**Comment by corus87** [comment]
Alright, thank you.
